/**
 * Static tenant branding — build-time baked.
 *
 * On the Codlylabs base build this file exports `null`: `useBranding()` falls
 * back to runtime resolution via `/api/v1/branding/resolve/{slug}` (the
 * original multi-tenant CSS-vars mode).
 *
 * On dedicated tenant builds (generated by `tenant_frontend_builder`), this
 * file is overwritten with a real `TENANT_STATIC_BRANDING` object — colors,
 * logo, login texts, etc. — so the bundle ships with the tenant identity
 * baked in and never fetches `/resolve/{slug}` at runtime.
 */

export interface TenantStaticBranding {
  slug: string
  brandName: string
  colors: {
    primary: string
    primaryDark: string
    accent: string
    surface: string
    textPrimary: string
    textSecondary: string
  }
  borderRadius: 'rounded' | 'sharp' | 'pill'
  logoUrl: string | null
  faviconUrl: string | null
  tagline: string | null
  loginTitle: string | null
  loginSubtitle: string | null
  loginHeroTitle: string | null
  loginHeroDescription: string | null
  badgeConfig: { position: string; style: string }
}

export const TENANT_STATIC_BRANDING: TenantStaticBranding | null = null
