import { Link } from 'react-router-dom'
import { useI18n } from '../i18n'
import { MessageSquare, Brain, Package, Map, Sparkles } from 'lucide-react'

export default function AboutPlatformPage() {
  const { t, language } = useI18n()
  const es = language === 'es'

  const modules = [
    {
      icon: MessageSquare,
      title: 'Discovery Agent',
      description: es
        ? 'Conversa contigo para entender el caso, resume el contexto y prepara la síntesis que dispara el diagnóstico.'
        : 'Talks with you to understand the case, summarizes context and prepares the synthesis that triggers the diagnosis.',
      requirement: es
        ? 'Compartí tu necesidad, tu industria y los procesos clave.'
        : 'Share your need, your industry and your key processes.',
    },
    {
      icon: Brain,
      title: es ? 'Diagnóstico estratégico' : 'Strategic Diagnosis',
      description: es
        ? 'Resume oportunidades, riesgos y KPIs con una propuesta priorizada lista para ser compartida con dirección.'
        : 'Summarizes opportunities, risks and KPIs with a prioritized proposal ready to share with leadership.',
      requirement: es
        ? 'Revisá y confirmá la síntesis que genera el agente.'
        : 'Review and confirm the synthesis generated by the agent.',
    },
    {
      icon: Package,
      title: es ? 'Documento de recomendación' : 'Recommendation Document',
      description: es
        ? 'Genera PDF/Word ejecutivos con ROI, métricas y roadmap para cada iniciativa.'
        : 'Generates executive PDF/Word documents with ROI, metrics and roadmap for each initiative.',
      requirement: es
        ? 'Descargá el archivo y compartílo con liderazgo o inversores.'
        : 'Download the file and share it with leadership or investors.',
    },
    {
      icon: Map,
      title: 'Vertical Pack',
      description: es
        ? 'Catálogo probado que combina plantillas, conectores y patrones de referencia regulatoria por industria.'
        : 'Proven catalog that combines templates, connectors and industry-specific regulatory reference patterns.',
      requirement: es
        ? 'Elegí un vertical (Retail, Salud, Finanzas, Logística) y seguí sus playbooks.'
        : 'Choose a vertical (Retail, Healthcare, Finance, Logistics) and follow its playbooks.',
    },
  ]

  return (
    <div className="min-h-screen bg-[#f8f9fa] flex flex-col">
      {/* Header */}
      <header className="fixed top-0 w-full z-50 bg-white/70 backdrop-blur-xl border-b border-indigo-500/10 shadow-sm shadow-indigo-500/5">
        <div className="flex items-center gap-4 px-6 py-4 max-w-7xl mx-auto">
          <Link to="/" className="text-indigo-600 hover:underline text-sm font-semibold">{t('footer.home')}</Link>
          <span className="text-gray-300">/</span>
          <span className="text-sm font-semibold text-gray-900">{es ? 'Sobre la plataforma' : 'About the platform'}</span>
        </div>
      </header>

      <main className="flex-grow pt-28 pb-20 px-6 max-w-5xl mx-auto w-full space-y-10">
        {/* Hero */}
        <section className="relative overflow-hidden rounded-2xl p-10 border border-gray-200/10"
          style={{ background: 'linear-gradient(135deg, rgba(228,223,255,0.3) 0%, #f8f9fa 50%, rgba(211,228,254,0.2) 100%)' }}>
          <div className="absolute -right-20 -top-20 w-64 h-64 bg-indigo-500/5 rounded-full blur-3xl" />
          <div className="relative z-10">
            <span className="text-xs uppercase tracking-widest text-indigo-600 font-bold">CodlyLabs</span>
            <h1 className="text-3xl md:text-4xl font-extrabold text-gray-900 mt-2 mb-3" style={{ fontFamily: 'Manrope, sans-serif' }}>
              {es ? 'Qué hace la plataforma' : 'What the platform does'}
            </h1>
            <p className="text-gray-500 max-w-2xl leading-relaxed">
              {es
                ? 'La solución combina descubrimiento guiado, diagnóstico estratégico y ejecución completa de PoCs con monitorización y recomendaciones automáticas para que puedas generar ROI con IA sin perder semanas.'
                : 'The platform combines guided discovery, strategic diagnosis and full PoC execution with monitoring and automatic recommendations so you can generate ROI with AI without wasting weeks.'}
            </p>
          </div>
        </section>

        {/* Capabilities Grid */}
        <section className="grid md:grid-cols-2 gap-6">
          {(es ? [
            { title: 'Descubrimiento', desc: 'Conversá con el Discovery Agent, respondé unas preguntas y observá cómo va creciendo el progreso en pantalla.' },
            { title: 'Diagnóstico', desc: 'Confirmá la síntesis y obtené un diagnóstico con riesgos, KPI y próximas oportunidades listo para compartir.' },
            { title: 'PoCs listas', desc: 'Cada plantilla incluye descripción, fases de implementación, métricas y conectores recomendados.' },
            { title: 'Roadmap de adopción', desc: 'Definí responsables, hitos de entrega y KPIs para transformar cada prueba en una secuencia repetible.' },
          ] : [
            { title: 'Discovery', desc: 'Talk with the Discovery Agent, answer a few questions and watch the progress grow on screen.' },
            { title: 'Diagnosis', desc: 'Confirm the synthesis and get a diagnosis with risks, KPIs and next opportunities ready to share.' },
            { title: 'Ready-made PoCs', desc: 'Each template includes description, implementation phases, metrics and recommended connectors.' },
            { title: 'Adoption Roadmap', desc: 'Define owners, delivery milestones and KPIs to turn each proof into a repeatable sequence.' },
          ]).map((item) => (
            <div key={item.title} className="bg-white rounded-2xl p-6 shadow-sm hover:shadow-md transition-shadow">
              <h2 className="font-bold text-gray-900 mb-2" style={{ fontFamily: 'Manrope, sans-serif' }}>{item.title}</h2>
              <p className="text-sm text-gray-500 leading-relaxed">{item.desc}</p>
            </div>
          ))}
        </section>

        {/* How to use */}
        <section className="bg-white rounded-2xl p-8 shadow-sm space-y-6">
          <h2 className="text-2xl font-bold text-gray-900" style={{ fontFamily: 'Manrope, sans-serif' }}>{es ? 'Cómo usar la plataforma' : 'How to use the platform'}</h2>
          <ol className="space-y-4">
            {(es ? [
              { step: 'Onboarding conversacional', desc: 'Ingresá tu necesidad en el chat y respondé las preguntas para que el Discovery Agent capture tu contexto.' },
              { step: 'Revisión del diagnóstico', desc: 'Leé el reporte, descargá el documento (PDF o Word) y compartílo con tu sponsor.' },
              { step: 'Seleccioná la PoC', desc: 'Cada vertical trae plantillas completas; bajá la que necesitás y conectá tus sistemas.' },
              { step: 'Escalamiento', desc: 'Priorizá la siguiente iniciativa con base en impacto, esfuerzo y dependencias.' },
            ] : [
              { step: 'Conversational onboarding', desc: 'Enter your need in the chat and answer the questions so the Discovery Agent captures your context.' },
              { step: 'Diagnosis review', desc: 'Read the report, download the document (PDF or Word) and share it with your sponsor.' },
              { step: 'Select the PoC', desc: 'Each vertical comes with complete templates; download what you need and connect your systems.' },
              { step: 'Scaling', desc: 'Prioritize the next initiative based on impact, effort and dependencies.' },
            ]).map((item, i) => (
              <li key={item.step} className="flex gap-4">
                <div className="flex-shrink-0 w-8 h-8 rounded-full bg-indigo-50 text-indigo-600 flex items-center justify-center font-bold text-sm">
                  {i + 1}
                </div>
                <div>
                  <span className="font-bold text-gray-900">{item.step}:</span>{' '}
                  <span className="text-gray-500">{item.desc}</span>
                </div>
              </li>
            ))}
          </ol>
        </section>

        {/* Modules */}
        <section className="bg-white rounded-2xl p-8 shadow-sm space-y-6">
          <h2 className="text-2xl font-bold text-gray-900" style={{ fontFamily: 'Manrope, sans-serif' }}>{es ? 'Módulos esenciales' : 'Core Modules'}</h2>
          <div className="grid md:grid-cols-2 gap-6">
            {modules.map((mod) => (
              <article key={mod.title} className="rounded-2xl bg-gray-50 p-6 space-y-3 hover:shadow-sm transition-shadow">
                <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center">
                  <mod.icon className="w-5 h-5" />
                </div>
                <h3 className="font-bold text-gray-900" style={{ fontFamily: 'Manrope, sans-serif' }}>{mod.title}</h3>
                <p className="text-sm text-gray-500">{mod.description}</p>
                <p className="text-xs text-indigo-600 font-semibold flex items-center gap-1">
                  <Sparkles className="w-3 h-3" /> {mod.requirement}
                </p>
              </article>
            ))}
          </div>
        </section>

        {/* Ready to use */}
        <section className="bg-white rounded-2xl p-8 shadow-sm space-y-4">
          <h2 className="text-2xl font-bold text-gray-900" style={{ fontFamily: 'Manrope, sans-serif' }}>{es ? 'PoCs listas para usar' : 'Ready-to-use PoCs'}</h2>
          <p className="text-gray-500">
            {es
              ? 'Cada PoC incluye descripción, etapas, KPIs y conectores. Podés adaptarlas rápidamente siguiendo el plan de implementación y cargando documentos o fuentes de datos adicionales desde el chat.'
              : 'Each PoC includes description, stages, KPIs and connectors. You can quickly adapt them by following the implementation plan and uploading documents or additional data sources from the chat.'}
          </p>
          <ul className="space-y-2">
            {(es ? [
              'Descargá el documento y compartilo con tu equipo.',
              'Usá los conectores recomendados (Salesforce, ServiceNow, Snowflake, etc.).',
              'Si necesitás contexto extra, subí archivos (PDF, DOCX, Excel) en el chat.',
            ] : [
              'Download the document and share it with your team.',
              'Use the recommended connectors (Salesforce, ServiceNow, Snowflake, etc.).',
              'If you need extra context, upload files (PDF, DOCX, Excel) in the chat.',
            ]).map((item) => (
              <li key={item} className="flex items-start gap-2 text-gray-500 text-sm">
                <span className="w-1.5 h-1.5 bg-indigo-600 rounded-full mt-2 flex-shrink-0" />
                {item}
              </li>
            ))}
          </ul>
        </section>
      </main>

      {/* Footer */}
      <footer className="w-full py-8 mt-auto bg-gray-50 border-t border-slate-200/50">
        <div className="flex flex-col md:flex-row justify-between items-center px-8 max-w-7xl mx-auto gap-4">
          <span className="text-sm text-slate-400">{t('footer.copyright', { year: new Date().getFullYear() })}</span>
          <nav className="flex gap-6">
            <Link to="/policies" className="text-sm text-slate-400 hover:text-indigo-500 transition-colors">{t('footer.privacy')}</Link>
            <Link to="/contact" className="text-sm text-slate-400 hover:text-indigo-500 transition-colors">{t('footer.contact')}</Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}
