/**
 * Discovery Summary Component
 * Displays the synthesis generated by the Discovery Agent for user confirmation
 */

import React from 'react';
import { CheckCircle, AlertCircle, Building2, Target, Database } from 'lucide-react';
import type { DiscoverySummary, DiscoveryProgressResponse } from '../types/discovery';

interface DiscoverySummaryProps {
  summary?: DiscoverySummary;
  progress?: DiscoveryProgressResponse;
  status: string;
  onConfirm?: () => void;
  onCorrect?: () => void;
}

export const DiscoverySummaryComponent: React.FC<DiscoverySummaryProps> = ({
  summary,
  progress,
  status,
  onConfirm,
  onCorrect,
}) => {
  // Show progress during conversation
  if (status === 'in_progress' && progress) {
    return (
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <h3 className="text-lg font-semibold text-gray-900 mb-4">
          Progreso del Descubrimiento
        </h3>

        <div className="space-y-3">
          <div className="flex items-center justify-between">
            <span className="text-sm text-gray-600">Completitud</span>
            <span className="text-sm font-medium text-brand-600">
              {progress.estimated_completion}
            </span>
          </div>

          <div className="w-full bg-gray-200 rounded-full h-2">
            <div
              className="bg-brand-600 h-2 rounded-full transition-all duration-300"
              style={{ width: progress.estimated_completion }}
            />
          </div>

          <div className="mt-4 space-y-2">
            <p className="text-sm font-medium text-gray-700">Objetivos Descubiertos:</p>
            {Object.entries(progress.objectives_achieved).map(([key, achieved]) => (
              <div key={key} className="flex items-center text-sm">
                {achieved ? (
                  <CheckCircle className="w-4 h-4 text-green-500 mr-2" />
                ) : (
                  <div className="w-4 h-4 border-2 border-gray-300 rounded-full mr-2" />
                )}
                <span className={achieved ? 'text-gray-700' : 'text-gray-400'}>
                  {key.replace(/_/g, ' ')}
                </span>
              </div>
            ))}
          </div>
        </div>
      </div>
    );
  }

  // Show summary for confirmation
  if (status === 'ready_for_confirmation' && summary) {
    return (
      <div className="bg-white rounded-lg shadow-sm border border-gray-200 p-6">
        <div className="flex items-center mb-4">
          <AlertCircle className="w-5 h-5 text-amber-500 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900">
            Síntesis del Descubrimiento
          </h3>
        </div>

        {/* Confidence Score */}
        <div className="mb-4 p-3 bg-brand-50 rounded-lg">
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium text-brand-900">
              Confianza del Diagnóstico
            </span>
            <span className="text-lg font-bold text-brand-600">
              {Math.round(summary.conversation_metadata.confidence_score * 100)}%
            </span>
          </div>
        </div>

        {/* Business Problem */}
        <div className="mb-4">
          <div className="flex items-start mb-2">
            <Target className="w-4 h-4 text-gray-500 mr-2 mt-1" />
            <div>
              <h4 className="text-sm font-semibold text-gray-700">
                Problema Identificado
              </h4>
              <p className="text-sm text-gray-600 mt-1">
                {summary.business_problem}
              </p>
            </div>
          </div>
        </div>

        {/* Business Objective */}
        <div className="mb-4">
          <div className="flex items-start mb-2">
            <CheckCircle className="w-4 h-4 text-gray-500 mr-2 mt-1" />
            <div>
              <h4 className="text-sm font-semibold text-gray-700">
                Objetivo de Negocio
              </h4>
              <p className="text-sm text-gray-600 mt-1">
                {summary.business_objective}
              </p>
            </div>
          </div>
        </div>

        {/* Organization Context */}
        <div className="mb-4">
          <div className="flex items-start mb-2">
            <Building2 className="w-4 h-4 text-gray-500 mr-2 mt-1" />
            <div className="flex-1">
              <h4 className="text-sm font-semibold text-gray-700 mb-2">
                Contexto Organizacional
              </h4>
              <div className="space-y-1 text-sm text-gray-600">
                <div className="flex justify-between">
                  <span>Industria:</span>
                  <span className="font-medium">{summary.organization_context.industry}</span>
                </div>
                <div className="flex justify-between">
                  <span>Tamaño:</span>
                  <span className="font-medium">{summary.organization_context.company_size}</span>
                </div>
                <div className="flex justify-between">
                  <span>Madurez Técnica:</span>
                  <span className="font-medium">{summary.organization_context.maturity_level}</span>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Data Landscape */}
        {summary.data_landscape.data_sources.length > 0 && (
          <div className="mb-4">
            <div className="flex items-start mb-2">
              <Database className="w-4 h-4 text-gray-500 mr-2 mt-1" />
              <div>
                <h4 className="text-sm font-semibold text-gray-700">
                  Datos Disponibles
                </h4>
                <div className="mt-1 flex flex-wrap gap-2">
                  {summary.data_landscape.data_sources.map((source, idx) => (
                    <span
                      key={idx}
                      className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-100 text-blue-800"
                    >
                      {source}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Volume Indicator */}
        {summary.data_landscape.volume_indicators && (
          <div className="mb-4 p-3 bg-gray-50 rounded-lg">
            <p className="text-sm text-gray-700">
              <span className="font-medium">Volumen: </span>
              {summary.data_landscape.volume_indicators.value}{' '}
              {summary.data_landscape.volume_indicators.metric}
            </p>
          </div>
        )}

        {/* Constraints */}
        {(summary.constraints.timeline || summary.constraints.compliance_requirements.length > 0) && (
          <div className="mb-6">
            <h4 className="text-sm font-semibold text-gray-700 mb-2">
              Restricciones
            </h4>
            <div className="space-y-1 text-sm text-gray-600">
              {summary.constraints.timeline && (
                <p>• Timeline: {summary.constraints.timeline}</p>
              )}
              {summary.constraints.budget_level !== 'Not Mentioned' && (
                <p>• Presupuesto: {summary.constraints.budget_level}</p>
              )}
              {summary.constraints.compliance_requirements.length > 0 && (
                <p>
                  • Compliance:{' '}
                  {summary.constraints.compliance_requirements.join(', ')}
                </p>
              )}
            </div>
          </div>
        )}

        {/* Missing Info Warning */}
        {summary.conversation_metadata.missing_critical_info.length > 0 && (
          <div className="mb-4 p-3 bg-amber-50 border border-amber-200 rounded-lg">
            <p className="text-sm font-medium text-amber-800 mb-1">
              Información Faltante
            </p>
            <ul className="text-xs text-amber-700 list-disc list-inside">
              {summary.conversation_metadata.missing_critical_info.map((info, idx) => (
                <li key={idx}>{info}</li>
              ))}
            </ul>
          </div>
        )}

        {/* Action Buttons */}
        <div className="flex gap-3 mt-6">
          <button
            onClick={onConfirm}
            className="flex-1 bg-brand-600 text-white px-4 py-2 rounded-lg font-medium hover:bg-brand-700 transition-colors"
          >
            ✓ Confirmar
          </button>
          <button
            onClick={onCorrect}
            className="flex-1 border border-gray-300 text-gray-700 px-4 py-2 rounded-lg font-medium hover:bg-gray-50 transition-colors"
          >
            Corregir
          </button>
        </div>
      </div>
    );
  }

  // Show completed state
  if (status === 'completed' && summary) {
    return (
      <div className="bg-white rounded-lg shadow-sm border border-green-200 p-6">
        <div className="flex items-center mb-4">
          <CheckCircle className="w-5 h-5 text-green-500 mr-2" />
          <h3 className="text-lg font-semibold text-gray-900">
            Descubrimiento Completado
          </h3>
        </div>
        <p className="text-sm text-gray-600 mb-4">
          Hemos completado el proceso de descubrimiento. Ahora generaremos el diagnóstico con las mejores soluciones de IA para tu caso.
        </p>
        <div className="p-3 bg-green-50 rounded-lg">
          <p className="text-sm font-medium text-green-800">
            ✓ Listo para diagnóstico
          </p>
        </div>
      </div>
    );
  }

  return null;
};

export default DiscoverySummaryComponent;
